# Generated by Django 3.2 on 2021-05-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='Data',
        ),
    ]
