# Generated by Django 3.1.7 on 2021-05-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_main_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pincode',
        ),
        migrations.AddField(
            model_name='data',
            name='contact',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
