# Generated by Django 3.1.7 on 2021-05-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210503_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='contact',
            field=models.TextField(),
        ),
    ]
